development:
  adapter: postgresql
  encoding: unicode
  database: angular_auth_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: angular_auth_test
  pool: 5
  username: postgres
  password: password
